// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ECustomerMsgType int32

const (
	ECustomerMsgType_TYPE_INVALID    ECustomerMsgType = 0
	ECustomerMsgType_REQ_LOGIN       ECustomerMsgType = 80000
	ECustomerMsgType_RESP_LOGIN      ECustomerMsgType = 80001
	ECustomerMsgType_REQ_HELLO       ECustomerMsgType = 80002
	ECustomerMsgType_RESP_HELLO      ECustomerMsgType = 80003
	ECustomerMsgType_REQ_JOIN_ROOM   ECustomerMsgType = 80004
	ECustomerMsgType_RESP_JOIN_ROOM  ECustomerMsgType = 80005
	ECustomerMsgType_REQ_LEAVE_ROOM  ECustomerMsgType = 80006
	ECustomerMsgType_RESP_LEAVE_ROOM ECustomerMsgType = 80007
	ECustomerMsgType_PUSH_SAY        ECustomerMsgType = 80008
	ECustomerMsgType_PUSH_JOIN       ECustomerMsgType = 80009
	ECustomerMsgType_PUSH_LEAVE      ECustomerMsgType = 80010
)

var ECustomerMsgType_name = map[int32]string{
	0:     "TYPE_INVALID",
	80000: "REQ_LOGIN",
	80001: "RESP_LOGIN",
	80002: "REQ_HELLO",
	80003: "RESP_HELLO",
	80004: "REQ_JOIN_ROOM",
	80005: "RESP_JOIN_ROOM",
	80006: "REQ_LEAVE_ROOM",
	80007: "RESP_LEAVE_ROOM",
	80008: "PUSH_SAY",
	80009: "PUSH_JOIN",
	80010: "PUSH_LEAVE",
}

var ECustomerMsgType_value = map[string]int32{
	"TYPE_INVALID":    0,
	"REQ_LOGIN":       80000,
	"RESP_LOGIN":      80001,
	"REQ_HELLO":       80002,
	"RESP_HELLO":      80003,
	"REQ_JOIN_ROOM":   80004,
	"RESP_JOIN_ROOM":  80005,
	"REQ_LEAVE_ROOM":  80006,
	"RESP_LEAVE_ROOM": 80007,
	"PUSH_SAY":        80008,
	"PUSH_JOIN":       80009,
	"PUSH_LEAVE":      80010,
}

func (x ECustomerMsgType) String() string {
	return proto.EnumName(ECustomerMsgType_name, int32(x))
}

func (ECustomerMsgType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

type LoginReq struct {
	Account              string   `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type LoginResp struct {
	Result               string   `protobuf:"bytes,1,opt,name=Result,proto3" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResp) Reset()         { *m = LoginResp{} }
func (m *LoginResp) String() string { return proto.CompactTextString(m) }
func (*LoginResp) ProtoMessage()    {}
func (*LoginResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{1}
}

func (m *LoginResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResp.Unmarshal(m, b)
}
func (m *LoginResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResp.Marshal(b, m, deterministic)
}
func (m *LoginResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResp.Merge(m, src)
}
func (m *LoginResp) XXX_Size() int {
	return xxx_messageInfo_LoginResp.Size(m)
}
func (m *LoginResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResp proto.InternalMessageInfo

func (m *LoginResp) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type HelloReq struct {
	Words                string   `protobuf:"bytes,1,opt,name=Words,proto3" json:"Words,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReq) Reset()         { *m = HelloReq{} }
func (m *HelloReq) String() string { return proto.CompactTextString(m) }
func (*HelloReq) ProtoMessage()    {}
func (*HelloReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{2}
}

func (m *HelloReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReq.Unmarshal(m, b)
}
func (m *HelloReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReq.Marshal(b, m, deterministic)
}
func (m *HelloReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReq.Merge(m, src)
}
func (m *HelloReq) XXX_Size() int {
	return xxx_messageInfo_HelloReq.Size(m)
}
func (m *HelloReq) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReq.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReq proto.InternalMessageInfo

func (m *HelloReq) GetWords() string {
	if m != nil {
		return m.Words
	}
	return ""
}

type HelloResp struct {
	Words                string   `protobuf:"bytes,1,opt,name=Words,proto3" json:"Words,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResp) Reset()         { *m = HelloResp{} }
func (m *HelloResp) String() string { return proto.CompactTextString(m) }
func (*HelloResp) ProtoMessage()    {}
func (*HelloResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{3}
}

func (m *HelloResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResp.Unmarshal(m, b)
}
func (m *HelloResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResp.Marshal(b, m, deterministic)
}
func (m *HelloResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResp.Merge(m, src)
}
func (m *HelloResp) XXX_Size() int {
	return xxx_messageInfo_HelloResp.Size(m)
}
func (m *HelloResp) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResp.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResp proto.InternalMessageInfo

func (m *HelloResp) GetWords() string {
	if m != nil {
		return m.Words
	}
	return ""
}

type RoomJoin struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomJoin) Reset()         { *m = RoomJoin{} }
func (m *RoomJoin) String() string { return proto.CompactTextString(m) }
func (*RoomJoin) ProtoMessage()    {}
func (*RoomJoin) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{4}
}

func (m *RoomJoin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomJoin.Unmarshal(m, b)
}
func (m *RoomJoin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomJoin.Marshal(b, m, deterministic)
}
func (m *RoomJoin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomJoin.Merge(m, src)
}
func (m *RoomJoin) XXX_Size() int {
	return xxx_messageInfo_RoomJoin.Size(m)
}
func (m *RoomJoin) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomJoin.DiscardUnknown(m)
}

var xxx_messageInfo_RoomJoin proto.InternalMessageInfo

func (m *RoomJoin) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RoomLeave struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomLeave) Reset()         { *m = RoomLeave{} }
func (m *RoomLeave) String() string { return proto.CompactTextString(m) }
func (*RoomLeave) ProtoMessage()    {}
func (*RoomLeave) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{5}
}

func (m *RoomLeave) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomLeave.Unmarshal(m, b)
}
func (m *RoomLeave) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomLeave.Marshal(b, m, deterministic)
}
func (m *RoomLeave) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomLeave.Merge(m, src)
}
func (m *RoomLeave) XXX_Size() int {
	return xxx_messageInfo_RoomLeave.Size(m)
}
func (m *RoomLeave) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomLeave.DiscardUnknown(m)
}

var xxx_messageInfo_RoomLeave proto.InternalMessageInfo

func (m *RoomLeave) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RoomResp struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomResp) Reset()         { *m = RoomResp{} }
func (m *RoomResp) String() string { return proto.CompactTextString(m) }
func (*RoomResp) ProtoMessage()    {}
func (*RoomResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{6}
}

func (m *RoomResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomResp.Unmarshal(m, b)
}
func (m *RoomResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomResp.Marshal(b, m, deterministic)
}
func (m *RoomResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomResp.Merge(m, src)
}
func (m *RoomResp) XXX_Size() int {
	return xxx_messageInfo_RoomResp.Size(m)
}
func (m *RoomResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomResp.DiscardUnknown(m)
}

var xxx_messageInfo_RoomResp proto.InternalMessageInfo

func (m *RoomResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RoomResp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func init() {
	proto.RegisterEnum("msg.ECustomerMsgType", ECustomerMsgType_name, ECustomerMsgType_value)
	proto.RegisterType((*LoginReq)(nil), "msg.LoginReq")
	proto.RegisterType((*LoginResp)(nil), "msg.LoginResp")
	proto.RegisterType((*HelloReq)(nil), "msg.HelloReq")
	proto.RegisterType((*HelloResp)(nil), "msg.HelloResp")
	proto.RegisterType((*RoomJoin)(nil), "msg.RoomJoin")
	proto.RegisterType((*RoomLeave)(nil), "msg.RoomLeave")
	proto.RegisterType((*RoomResp)(nil), "msg.RoomResp")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899) }

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 353 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xcf, 0x4f, 0xe2, 0x40,
	0x14, 0xc7, 0x97, 0xdd, 0x81, 0x6d, 0x5f, 0x76, 0x61, 0x32, 0xcb, 0x6e, 0x38, 0xad, 0x58, 0x3d,
	0x18, 0x0f, 0x5e, 0x4c, 0xbc, 0x37, 0x38, 0x91, 0x92, 0xd2, 0xc2, 0x80, 0x18, 0x4e, 0x0d, 0xc2,
	0xa4, 0x21, 0xa1, 0x4c, 0xed, 0x80, 0x89, 0x37, 0x7f, 0xff, 0xfa, 0x6f, 0x7b, 0xf0, 0x6e, 0x3a,
	0xd3, 0x06, 0x0f, 0x7a, 0x9b, 0xef, 0xe7, 0x7d, 0xfa, 0xde, 0xf7, 0x50, 0x30, 0x23, 0x19, 0x1e,
	0xc4, 0x89, 0x58, 0x09, 0xf2, 0x23, 0x92, 0xa1, 0xb5, 0x0b, 0x86, 0x2b, 0xc2, 0xf9, 0x92, 0xf1,
	0x0b, 0xd2, 0x80, 0x9f, 0xf6, 0x74, 0x2a, 0xd6, 0xcb, 0x55, 0xa3, 0xd4, 0x2c, 0xed, 0x99, 0xac,
	0x88, 0xd6, 0x0e, 0x98, 0xb9, 0x25, 0x63, 0xf2, 0x0f, 0x2a, 0x8c, 0xcb, 0xf5, 0xa2, 0xb0, 0xf2,
	0x64, 0x35, 0xc1, 0x68, 0xf3, 0xc5, 0x42, 0x64, 0xab, 0xea, 0x50, 0x3e, 0x13, 0xc9, 0x4c, 0xe6,
	0x8a, 0x0e, 0xd6, 0x36, 0x98, 0xb9, 0x21, 0xe3, 0x2f, 0x94, 0xff, 0x60, 0x30, 0x21, 0xa2, 0x8e,
	0x98, 0x2f, 0x09, 0x01, 0xe4, 0x4d, 0x22, 0x9e, 0x0b, 0xea, 0x6d, 0x6d, 0x81, 0x99, 0xcd, 0x5d,
	0x3e, 0xb9, 0xe4, 0x9f, 0x0a, 0x47, 0x7a, 0x81, 0x3a, 0x41, 0x00, 0xb5, 0xc4, 0x4c, 0xcf, 0xcb,
	0x4c, 0xbd, 0xb3, 0xf6, 0x34, 0x49, 0xba, 0x32, 0x6c, 0x7c, 0xd7, 0xed, 0x75, 0xda, 0x7f, 0x2b,
	0x01, 0xa6, 0xad, 0xb5, 0x5c, 0x89, 0x88, 0x67, 0x60, 0x78, 0x15, 0x73, 0x82, 0xe1, 0xd7, 0x70,
	0xdc, 0xa3, 0x81, 0xe3, 0x8d, 0x6c, 0xd7, 0x39, 0xc6, 0xdf, 0x48, 0x0d, 0x4c, 0x46, 0xfb, 0x81,
	0xeb, 0x9f, 0x38, 0x1e, 0xbe, 0x4e, 0x11, 0xc1, 0x00, 0x8c, 0x0e, 0x7a, 0x39, 0xb9, 0x49, 0x51,
	0xa1, 0xb4, 0xa9, 0xeb, 0xfa, 0xf8, 0xf6, 0x83, 0xa2, 0xc9, 0x5d, 0x8a, 0xc8, 0x1f, 0xf8, 0x9d,
	0x29, 0x1d, 0xdf, 0xf1, 0x02, 0xe6, 0xfb, 0x5d, 0x7c, 0x9f, 0x22, 0x52, 0x87, 0xaa, 0xd2, 0x36,
	0xf4, 0xa1, 0xa0, 0xfd, 0xc0, 0xa5, 0xf6, 0x88, 0x6a, 0xfa, 0x98, 0x22, 0xf2, 0x17, 0x6a, 0xfa,
	0xea, 0x06, 0x3f, 0xa5, 0x88, 0x54, 0xc1, 0xe8, 0x9d, 0x0e, 0xda, 0xc1, 0xc0, 0x1e, 0xe3, 0x67,
	0x5d, 0x45, 0xe5, 0x6c, 0x25, 0x7e, 0xd1, 0x55, 0x14, 0x50, 0xdf, 0xe1, 0xd7, 0x14, 0x9d, 0x57,
	0xd4, 0xcf, 0x70, 0xf8, 0x1e, 0x00, 0x00, 0xff, 0xff, 0xaf, 0x99, 0x4a, 0x2d, 0x19, 0x02, 0x00,
	0x00,
}
